# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "mint"

# Site settings
locale: "en-US"
title: "@dgaubert"
title_separator: "-"
name: "Daniel G.ª Aubert"

include: ["_pages", "_posts"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Social Sharing
twitter:
  username: "@danigaubert"

# Site Author
author:
  name: "Daniel G.ª Aubert"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I build software."
  location: "Madrid"
  email: "danielgarciaaubert@gmail.com"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: https://www.dgaubert.com
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: https://twitter.com/danigaubert
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/dgaubert

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/danigaubert"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dgaubert"

plugins:
  - jekyll-include-cache
